# permissions for end users to edit kafkas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kafka-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kafka-operator
    app.kubernetes.io/part-of: kafka-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafka-editor-role
rules:
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - kafkas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - kafkas/status
  verbs:
  - get
