# permissions for end users to view kafkas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kafka-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kafka-operator
    app.kubernetes.io/part-of: kafka-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafka-viewer-role
rules:
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - kafkas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - kafkas/status
  verbs:
  - get
